# Generated by Django 5.0.7 on 2024-08-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('number_of_seats', models.IntegerField()),
            ],
        ),
    ]
